name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Install xk6
      run: go install go.k6.io/xk6/cmd/xk6@latest

    - name: Build k6 with extension
      run: xk6 build --with github.com/VikashChauhan51/k6-jsonnet@v0.1.0

    - name: Run tests
      run: go test ./...
